spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 20001114
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

mybatis:
  config-location: classpath:SqlMapConfig.xml
  mapper-locations: classpath:com/gcl/demo1/dao/mybatis/*Dao.xml

logging:
  level:
    root: info
    com.gcl: debug
  file:
    name: log/blog-dev.log

server:
  port: 8888