spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: xxxxxxxx
  redis:
    database: 0             # redis数据库索引（默认为0）
    host: xxxxxxxxxxxxxx    # redis的服务器地址
    port: 6379              # redis的服务器端口号
    password: 12345678      # redis连接密码
    jedis:
      pool:
        max-idle: 8         # 连接池中的最大空闲连接
        min-idle: 0         # 连接池中的最小空闲连接
    timeout: 300

mybatis:
  mapper-locations: classpath:mapping/*Dao.xml
  type-aliases-package: com.gcl.demo1.entity

logging:
  level:
    root: info
    com.gcl: debug
  file:
    name: log/blog-dev.log

server:
  port: 8888
  servlet:
    session:
      timeout: 864000